services:
  postgres:
    env_file: .env
    container_name: ${APP_NAME}_postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSRGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - data_postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app_network
    restart: on-failure

  redis:
    env_file: .env
    container_name: ${APP_NAME}_redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app_network
    restart: on-failure

  rabbit:
    env_file: .env
    container_name: ${APP_NAME}_amqp
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"

    networks:
      - app_network
    restart: on-failure

  # mail-microservice:
  #   build:
  #     context: ../mail-microservice
  #     dockerfile: ../mail-microservice/Dockerfile
  #   container_name: mail-microservice
  #   environment:
  #     NODE_ENV: production
  #   env_file:
  #     - ../mail-microservice/.env
  #   depends_on:
  #     - rabbit
  #   ports:
  #     - "5001:5001"
  #   networks:
  #     - app_network
  #   restart: unless-stopped

  # user-microservice:
  #   build:
  #     context: ../user-microservice
  #     dockerfile: ../user-microservice/Dockerfile
  #   container_name: user-microservice
  #   environment:
  #     NODE_ENV: production
  #   env_file:
  #     - ../user-microservice/.env
  #   depends_on:
  #     - rabbit
  #     - redis
  #     - postgres
  #   ports:
  #     - "5002:5002"
  #   networks:
  #     - app_network
  #   restart: unless-stopped

volumes:
  data_postgres:

networks:
  app_network:
