FROM node:20-alpine as builder
WORKDIR /cht/src/app

COPY package*.json ./
RUN npm install
RUN npm i @noildm/contracts@latest

COPY . .
RUN npm run build

FROM node:20-alpine
ENV NODE_ENV=production
WORKDIR /cht/src/app
COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /chat/src/app/dist ./dist

USER node
CMD ["node", "dist/main.js"]
